version: "3.8"


services:
  pg:
    image: postgres
    container_name: pg
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${PWD}/src/app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}


